# Netlify Configuration for Choice Insurance Agency

[build]
  # For static HTML sites, no build command needed
  command = ""
  # Publish directory for static files
  publish = "."

[build.environment]
  # Node version for any build processes
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://fonts.googleapis.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https://www.google-analytics.com;
      frame-src 'self' https://www.googletagmanager.com;
    """
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

# Cache static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML files should not be cached as aggressively
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirects for clean URLs and SEO
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Handle trailing slashes
[[redirects]]
  from = "/about/"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/contact/"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/services/"
  to = "/services.html"
  status = 200

# 404 fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

